---
- name: Ensure docker daemon is running
  service: name=docker state=started
- name: Read docker info
  command: docker info
  register: dockerInfoCmd
  changed_when: false
- name: Set active swarm manager fact
  set_fact: activeSwarmManager=yes
  when:
    - "'Swarm: active' in dockerInfoCmd.stdout"
    - "'Is Manager: true' in dockerInfoCmd.stdout"
- name: Set inactive swarm manager fact
  set_fact: activeSwarmManager=no
  when:
    - "'Swarm: inactive' in dockerInfoCmd.stdout"
- name: Group active swarm managers
  group_by: key=activeSwarmManager_{{activeSwarmManager}}
- name: Read the swarm manager token
  command: docker swarm join-token manager -q
  register: swarmManagerTokenCmd
  when: activeSwarmManager
  changed_when: false
- name: Declare the manager token as a fact
  set_fact: swarmManagerToken="{{ swarmManagerTokenCmd.stdout }}"
  when: activeSwarmManager
- name: Read the swarm worker token
  command: docker swarm join-token worker -q
  register: swarmWorkerTokenCmd
  when: activeSwarmManager
  changed_when: false
- name: Declare the worker token as a fact
  set_fact: swarmWorkerToken="{{ swarmWorkerTokenCmd.stdout }}"
  when: activeSwarmManager
